# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CS4PS @ UON 2017
email: daniel.hickmott@uon.edu.au
contact: Daniel Hickmott
baseurl: "/ps-2017"

# Google services
google_analytics: UA-87991896-1

# Content Pages Paths
resources_path: "/resources"
extras_path: "/extras/"
previous_year_extras_path: "https://cs4s.github.io/ps-2016/extras/"

# Day 1 Paths
day1_path: "/day1/"
visual_programming_path: "/day1/visual_programming/"
previous_year_visual_programming_path: "https://cs4s.github.io/ps-2016/day1/visualprogramming/"
robotics_path: "/day1/robotics/"
cs_unplugged_path: "/day1/cs_unplugged/"

# Day 2 Paths
day2_path: "/day2/"
creative_computing_path: "/day2/creative_computing/"
lesson_planning_path: "/day2/lesson_planning/"
physical_computing_path: "/day2/physical_computing/"
previous_year_physical_computing_path: "https://cs4s.github.io/ps-2016/day2/physicalcomputing/"
sharing_path: "/day2/sharing/"

# Build settings
markdown: kramdown
